/usr/bin/pigz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_Pong_deletion_derivative/pacbio_NB/fastq/WGS/Rice3k_CAAS/ping_coverage_3k/B026.ping.coverage.txt -p 4
/usr/bin/pigz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_Pong_deletion_derivative/pacbio_NB/fastq/WGS/Rice3k_CAAS/ping_coverage_3k/B030.ping.coverage.txt -p 4
/usr/bin/pigz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_Pong_deletion_derivative/pacbio_NB/fastq/WGS/Rice3k_CAAS/ping_coverage_3k/B032.ping.coverage.txt -p 4
/usr/bin/pigz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_Pong_deletion_derivative/pacbio_NB/fastq/WGS/Rice3k_CAAS/ping_coverage_3k/B034.ping.coverage.txt -p 4
/usr/bin/pigz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_Pong_deletion_derivative/pacbio_NB/fastq/WGS/Rice3k_CAAS/ping_coverage_3k/B036.ping.coverage.txt -p 4
/usr/bin/pigz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_Pong_deletion_derivative/pacbio_NB/fastq/WGS/Rice3k_CAAS/ping_coverage_3k/B040.ping.coverage.txt -p 4
/usr/bin/pigz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_Pong_deletion_derivative/pacbio_NB/fastq/WGS/Rice3k_CAAS/ping_coverage_3k/B044.ping.coverage.txt -p 4
/usr/bin/pigz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_Pong_deletion_derivative/pacbio_NB/fastq/WGS/Rice3k_CAAS/ping_coverage_3k/B046.ping.coverage.txt -p 4
/usr/bin/pigz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_Pong_deletion_derivative/pacbio_NB/fastq/WGS/Rice3k_CAAS/ping_coverage_3k/B048.ping.coverage.txt -p 4
