pdf("multi_run_color_defined.pdf", width=14, height=18)
layout(matrix(1:14, 14, 1), rep(1, 13))
#order: bottom, left, top, and right. The default is c(5.1, 4.1, 4.1, 2.1).
par(mar=c(1,1,1,7))
for (i in 2:13){
    filename <- paste("core_v0.7.pruneddata3.", i, ".Q.reordered.txt", sep="")
    tbl <- read.table(filename, sep="\t")
    colname  <- paste("core_v0.7.pruneddata3.", i, ".Q.color.txt", sep="")
    color <- read.table(colname, sep="\t")
    barplot(t(as.matrix(tbl)), space = c(0.2), col=as.vector(color$V3), xlab="", ylab="", border=NA, horiz=FALSE, axes=FALSE)
    #mtext(paste("K = ", i, sep=""), side = 4, font=1, at = 0.4, line=1, cex=1.4, col="black")
    text(3700, 0.5, labels = paste("K = ", i, sep=""), cex=3, col="black", srt = 0, adj = 0, xpd = TRUE)
}
i = 14
filename <- paste("core_v0.7.pruneddata3.", i, ".Q.reordered.txt", sep="")
tbl <- read.table(filename, sep="\t")
colname  <- paste("core_v0.7.pruneddata3.", i, ".Q.color.txt", sep="")
color <- read.table(colname, sep="\t")
barplot(t(as.matrix(tbl)), space = c(0.2), col=as.vector(color$V3), xlab="", ylab="", border=NA, horiz=FALSE, axes=FALSE)
text(3700, 0.5, labels = paste("K = ", i, sep=""), cex=3, col="black", srt = 0, adj = 0, xpd = TRUE)
mtext("TRJ", side = 1, font=1, at = 200, line= 4, cex=2, col="cornflowerblue")
mtext("TEJ", side = 1, font=1, at = 800, line= 4, cex=2, col="blue")
mtext("ARO", side = 1, font=1, at = 1100, line= 4, cex=2, col="darkorchid")
mtext("AUS", side = 1, font=1, at = 1350, line= 4, cex=2, col="chocolate")
mtext("IND", side = 1, font=1, at = 2500, line= 4, cex=2, col="green")
#text(200, 0, labels = "TRJ", cex=3, col="black", srt = 0, adj = 0, xpd = TRUE)
#text(500, -0.5, labels = "TEJ", cex=3, col="black", srt = 0, adj = 0, xpd = TRUE)
#text(600, -0.5, labels = "ARO", cex=3, col="black", srt = 0, adj = 0, xpd = TRUE)
#text(800, -0.5, labels = "AUS", cex=3, col="black", srt = 0, adj = 0, xpd = TRUE)
#text(2400, -0.5, labels = "IND", cex=3, col="black", srt = 0, adj = 0, xpd = TRUE)
