/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.12/bin/bwa mem /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_Round3_Pseudo.fa /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470252_1.fastq.gz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470252_2.fastq.gz | /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -F4 -bS -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470252_Pseudo.raw.bam -
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools sort -m 1000000000 /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470252_Pseudo.raw.bam /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470252_Pseudo
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -h /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470252_Pseudo.bam | perl -lane 'if($F[11] =~ /^NM:i:(\d+)$/){print if $1<=2}else{print}'| /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -bS - -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470252_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470252_Pseudo.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470252_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.12/bin/bwa mem /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_Round3_Pseudo.fa /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470279_1.fastq.gz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470279_2.fastq.gz | /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -F4 -bS -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470279_Pseudo.raw.bam -
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools sort -m 1000000000 /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470279_Pseudo.raw.bam /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470279_Pseudo
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -h /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470279_Pseudo.bam | perl -lane 'if($F[11] =~ /^NM:i:(\d+)$/){print if $1<=2}else{print}'| /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -bS - -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470279_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470279_Pseudo.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470279_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.12/bin/bwa mem /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_Round3_Pseudo.fa /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470300_1.fastq.gz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470300_2.fastq.gz | /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -F4 -bS -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470300_Pseudo.raw.bam -
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools sort -m 1000000000 /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470300_Pseudo.raw.bam /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470300_Pseudo
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -h /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470300_Pseudo.bam | perl -lane 'if($F[11] =~ /^NM:i:(\d+)$/){print if $1<=2}else{print}'| /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -bS - -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470300_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470300_Pseudo.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470300_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.12/bin/bwa mem /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_Round3_Pseudo.fa /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470383_1.fastq.gz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470383_2.fastq.gz | /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -F4 -bS -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470383_Pseudo.raw.bam -
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools sort -m 1000000000 /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470383_Pseudo.raw.bam /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470383_Pseudo
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -h /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470383_Pseudo.bam | perl -lane 'if($F[11] =~ /^NM:i:(\d+)$/){print if $1<=2}else{print}'| /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -bS - -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470383_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470383_Pseudo.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470383_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.12/bin/bwa mem /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_Round3_Pseudo.fa /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470404_1.fastq.gz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470404_2.fastq.gz | /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -F4 -bS -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470404_Pseudo.raw.bam -
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools sort -m 1000000000 /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470404_Pseudo.raw.bam /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470404_Pseudo
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -h /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470404_Pseudo.bam | perl -lane 'if($F[11] =~ /^NM:i:(\d+)$/){print if $1<=2}else{print}'| /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -bS - -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470404_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470404_Pseudo.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470404_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.12/bin/bwa mem /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_Round3_Pseudo.fa /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470480_1.fastq.gz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470480_2.fastq.gz | /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -F4 -bS -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470480_Pseudo.raw.bam -
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools sort -m 1000000000 /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470480_Pseudo.raw.bam /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470480_Pseudo
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -h /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470480_Pseudo.bam | perl -lane 'if($F[11] =~ /^NM:i:(\d+)$/){print if $1<=2}else{print}'| /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -bS - -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470480_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470480_Pseudo.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470480_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.12/bin/bwa mem /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_Round3_Pseudo.fa /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470491_1.fastq.gz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470491_2.fastq.gz | /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -F4 -bS -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470491_Pseudo.raw.bam -
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools sort -m 1000000000 /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470491_Pseudo.raw.bam /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470491_Pseudo
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -h /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470491_Pseudo.bam | perl -lane 'if($F[11] =~ /^NM:i:(\d+)$/){print if $1<=2}else{print}'| /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -bS - -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470491_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470491_Pseudo.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470491_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.12/bin/bwa mem /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_Round3_Pseudo.fa /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470492_1.fastq.gz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470492_2.fastq.gz | /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -F4 -bS -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470492_Pseudo.raw.bam -
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools sort -m 1000000000 /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470492_Pseudo.raw.bam /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470492_Pseudo
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -h /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470492_Pseudo.bam | perl -lane 'if($F[11] =~ /^NM:i:(\d+)$/){print if $1<=2}else{print}'| /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -bS - -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470492_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470492_Pseudo.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470492_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.12/bin/bwa mem /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_Round3_Pseudo.fa /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470510_1.fastq.gz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470510_2.fastq.gz | /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -F4 -bS -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470510_Pseudo.raw.bam -
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools sort -m 1000000000 /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470510_Pseudo.raw.bam /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470510_Pseudo
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -h /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470510_Pseudo.bam | perl -lane 'if($F[11] =~ /^NM:i:(\d+)$/){print if $1<=2}else{print}'| /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -bS - -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470510_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470510_Pseudo.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round3/ERS470510_Pseudo.NM2.bam
