/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.12/bin/bwa mem /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_Round0_Pseudo.fa /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468186_1.fastq.gz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468186_2.fastq.gz | /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -F4 -bS -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468186_Pseudo.raw.bam -
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools sort -m 1000000000 /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468186_Pseudo.raw.bam /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468186_Pseudo
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -h /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468186_Pseudo.bam | perl -lane 'if($F[11] =~ /^NM:i:(\d+)$/){print if $1<=2}else{print}'| /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -bS - -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468186_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468186_Pseudo.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468186_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.12/bin/bwa mem /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_Round0_Pseudo.fa /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468298_1.fastq.gz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468298_2.fastq.gz | /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -F4 -bS -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468298_Pseudo.raw.bam -
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools sort -m 1000000000 /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468298_Pseudo.raw.bam /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468298_Pseudo
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -h /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468298_Pseudo.bam | perl -lane 'if($F[11] =~ /^NM:i:(\d+)$/){print if $1<=2}else{print}'| /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -bS - -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468298_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468298_Pseudo.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468298_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.12/bin/bwa mem /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_Round0_Pseudo.fa /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468595_1.fastq.gz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468595_2.fastq.gz | /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -F4 -bS -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468595_Pseudo.raw.bam -
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools sort -m 1000000000 /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468595_Pseudo.raw.bam /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468595_Pseudo
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -h /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468595_Pseudo.bam | perl -lane 'if($F[11] =~ /^NM:i:(\d+)$/){print if $1<=2}else{print}'| /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -bS - -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468595_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468595_Pseudo.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468595_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.12/bin/bwa mem /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_Round0_Pseudo.fa /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468605_1.fastq.gz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468605_2.fastq.gz | /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -F4 -bS -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468605_Pseudo.raw.bam -
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools sort -m 1000000000 /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468605_Pseudo.raw.bam /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468605_Pseudo
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -h /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468605_Pseudo.bam | perl -lane 'if($F[11] =~ /^NM:i:(\d+)$/){print if $1<=2}else{print}'| /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -bS - -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468605_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468605_Pseudo.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS468605_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.12/bin/bwa mem /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_Round0_Pseudo.fa /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS469412_1.fastq.gz /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS469412_2.fastq.gz | /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -F4 -bS -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS469412_Pseudo.raw.bam -
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools sort -m 1000000000 /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS469412_Pseudo.raw.bam /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS469412_Pseudo
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -h /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS469412_Pseudo.bam | perl -lane 'if($F[11] =~ /^NM:i:(\d+)$/){print if $1<=2}else{print}'| /opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools view -bS - -o /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS469412_Pseudo.NM2.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS469412_Pseudo.bam
/opt/linux/centos/7.x/x86_64/pkgs/samtools/0.1.19/bin/samtools index /bigdata/wesslerlab/shared/Rice/Rice_population_sequence/Rice_3000/analysis/Ping_missed_indica_pseudogenome/Ping_test_Round0/ERS469412_Pseudo.NM2.bam
