pdf("mPing_Ping_Pong_percent.pdf")
par(mar=c(6,5,4,2))
x <- read.table("mPing_Ping_Pong_percent.txt", sep="\t", header=TRUE)
data <- rbind(x$mPing, x$Ping, x$Pong)
xx <- barplot(data, beside=TRUE, border=FALSE, ylim=c(0, 1), cex=1.4, cex.axis=1.4, cex.lab=1.4, col=c("Orange", "blue", "chocolate"))
axis(1, c(0.5, max(xx)+0.9), line=0, labels=c("",""))
par(font=3)
text(xx[1,]+0.2, rep(-0.12, 6), offset=2, cex=1.4, labels=x$Group, srt=45, xpd=TRUE)
legend(max(xx)-18, 1.1, c("mPing", "Ping", "Pong"), bty="n", border="NA", lty=c(0,0,0), cex=1.4, fill=c("orange", "blue", "chocolate"), ncol = 3, xpd=TRUE)
par(font=1)
mtext("Percenatage of strains have", side=2, at=0.3, line=3, cex=1.4)
mtext("mPing/Ping/Pong", side=2, font=3, at=0.78, line=3, cex=1.4)
dev.off()
